# Generated by Django 4.1.2 on 2022-10-16 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_customer_first_name_alter_customer_last_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('lgbm', 'LightGBM'), ('xgb', 'XGBoost'), ('ada', 'AdaBoost'), ('cat', 'CatBoost'), ('svr', 'SVR')], default='lgbm', max_length=4)),
                ('comp_code', models.CharField(max_length=6)),
            ],
        ),
    ]
