# Generated by Django 4.1.2 on 2022-10-16 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_forecast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(choices=[('lgbm', 'LightGBM'), ('xgb', 'XGBoost'), ('svm', 'SVM')], default='lgbm', max_length=4)),
                ('file', models.FileField(upload_to='')),
                ('target', models.CharField(max_length=256)),
            ],
        ),
    ]
