# Generated by Django 4.1.2 on 2022-10-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='date_end',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='date_st',
            field=models.DateTimeField(null=True),
        ),
    ]
