# Generated by Django 4.1.2 on 2022-10-16 04:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_forecast_date_end_forecast_date_st'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='date_end',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='date_st',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 17, 11, 54, 10, 202019)),
        ),
    ]
