name: Python application 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services: 
      postgres:
        image: postgres:latest
        env: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: django-ml
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps: 
    - uses: actions/checkout@v2 
    - name: Set up Python 3.9
      uses: actions/setup-python@v2 
      with: 
        python-version: 3.9

    - name: pyscopg2 prerequirities
      run: sudo apt-get install libpq-dev

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-django
        pip install -r requirements.txt

    - name: Run migrations 
      run: python manage.py migrate
    - name: Run test
      run: python manage.py test
